stages:
  - lint
  - test
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"
  PYTHONPATH: "$CI_PROJECT_DIR"
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE: emilie2393/oc_lettings
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"
  PYTHONPATH: "$CI_PROJECT_DIR"
  CONTAINER_NAME: oc_lettings_site
  RENDER_HOOK: "https://api.render.com/deploy/srv-cuqb62lds78s739ak1g0?key=wrz_P66XA-E"


cache:
  paths:
    - .pip_cache/

linting:
  stage: lint
  image: python:3.9
  before_script:
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  script:
    - flake8
  allow_failure: false

tests:
  stage: test
  image: python:3.9
  before_script:
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  script:
    - pytest --cov=oc_lettings_site --cov-report=term-missing --cov-fail-under=80
  coverage: '/^TOTAL.*\s+(\d+)%/'
  allow_failure: false

build_docker_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Authentification sur Docker Hub"
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - echo "Construction de l'image Docker"
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE:latest
    - echo "Pousser l'image sur Docker Hub"
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_IMAGE:latest
  only:
    - main
  artifacts:
    paths:
      - Dockerfile

deploy_to_render:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - echo "Déclenchement du déploiement sur Render..."
    - apk add --no-cache jq  # Installation de jq (nécessaire pour traiter la réponse JSON)
    
    # Déclencher le déploiement sur Render
    - |
      DEPLOY_RESPONSE=$(curl -s -X POST "$RENDER_HOOK" -H "Accept: application/json")
      echo "Réponse Render: $DEPLOY_RESPONSE"

      DEPLOY_ID=$(echo $DEPLOY_RESPONSE | jq -r '.id')

      if [[ "$DEPLOY_ID" == "null" || -z "$DEPLOY_ID" ]]; then
        echo "🚨 Erreur : Impossible d'obtenir l'ID du déploiement"
        exit 1
      fi

      echo "Déploiement en cours avec ID: $DEPLOY_ID"

    # Vérifier le statut du déploiement
    - echo "Vérification du statut du déploiement..."
    - |
      STATUS="in_progress"
      while [[ "$STATUS" == "in_progress" || "$STATUS" == "queued" ]]; do
        sleep 10  # Attendre 10 secondes avant de revérifier
        STATUS=$(curl -s -X GET "https://api.render.com/v1/deploys/$DEPLOY_ID" -H "Accept: application/json" | jq -r '.status')
        echo "Statut actuel: $STATUS"
      done

    # Vérification finale du statut
    - |
      if [[ "$STATUS" != "live" ]]; then
        echo "🚨 Le déploiement a échoué !"
        exit 1
      else
        echo "✅ Déploiement réussi !"
      fi
  only:
    - main



