stages:
  - build
  - lint
  - test
  - deploy

variables:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE: emilie2393/oc_lettings
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"
  PYTHONPATH: "$CI_PROJECT_DIR"
  CONTAINER_NAME: oc_lettings_site  # Nom personnalisé du conteneur

cache:
  paths:
    - .pip_cache/

build_docker_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Authentification sur Docker Hub"
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - echo "Construction de l'image Docker"
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - echo "Pousser l'image sur Docker Hub"
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - main
  artifacts:
    paths:
      - Dockerfile

linting:
  stage: lint
  image: $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - flake8
  allow_failure: false

tests:
  stage: test
  image: $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - pytest --cov=oc_lettings_site --cov-report=term-missing --cov-fail-under=80
  coverage: '/^TOTAL.*\s+(\d+)%/'
  allow_failure: false

deploy_local:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    IMAGE_NAME: $DOCKER_IMAGE
    DOCKER_TAG: $CI_COMMIT_SHORT_SHA
  script:
    - echo "Checking Docker version"
    - docker --version  # Affiche la version de Docker

    # Étape : Arrêter et supprimer le conteneur existant si nécessaire
    - echo "Arrêt et suppression du conteneur existant (s'il existe)..."
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true

    - echo "Checking if port 8000 is in use..."
    # Vérifier si le port 8000 est occupé
    - if netstat -tuln | grep ':8000' > /dev/null; then
        echo "Port 8000 is in use. Killing the process...";
        PROCESS_ID=$(netstat -tulnp | grep ':8000' | awk '{print $6}' | cut -d'/' -f1);
        kill -9 $PROCESS_ID || true;
      else
        echo "Port 8000 is free.";
      fi
    - echo "Checking Docker containers using port 8000..."
    # Vérifier et arrêter les conteneurs Docker utilisant le port 8000
    - docker ps -q --filter "publish=8000" | xargs -r docker stop
    - docker ps -q --filter "publish=8000" | xargs -r docker rm

    # Étape : Pull de l'image Docker
    - echo "Pulling Docker image..."
    - docker pull $IMAGE_NAME:$DOCKER_TAG

    # Étape : Exécution du conteneur et collecte des fichiers statiques
    - echo "Démarrage du conteneur et collecte des fichiers statiques..."
    - docker run --name $CONTAINER_NAME -d -p 8000:8000 $IMAGE_NAME:$DOCKER_TAG

    # Étape : Collecte des fichiers statiques dans le conteneur
    - docker exec $CONTAINER_NAME python manage.py collectstatic --noinput

    # Étape : Affichage des conteneurs en cours d'exécution
    - echo "Conteneur en cours d'exécution :"
    - docker ps
  when: manual

