image: python:3.9

stages:
  - lint
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"
  PYTHONPATH: "$CI_PROJECT_DIR"

cache:
  paths:
    - .pip_cache/

before_script:
  - apt-get update && apt-get install -y python3-venv
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

linting:
  stage: lint
  script:
    - flake8
  allow_failure: false

tests:
  stage: test
  script:
    - pytest --cov=oc_lettings_site --cov-report=term-missing --cov-fail-under=80
  coverage: '/^TOTAL.*\s+(\d+)%/'
  allow_failure: false


