# Generated by Django 3.0 on 2024-12-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0004_auto_20241107_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
    ]
