# Generated by Django 3.0 on 2024-12-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_auto_20241211_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
